### ISSUE TITLE
问题：计算具有biased的顶点法向量，代码中是不是需要关于顶点做个轮换

### ISSUE THREAD

**Issue by gaoxinge** [parallel101/opengltutor#46]
@archibate 

现代码中，基于顶点`a`计算出具有`biased`的顶点法向量后，会依次赋值给`a`, `b`, `c`三个顶点：

https://github.com/parallel101/opengltutor/blob/817754a02e03f7b531e6be9366fec3ebb6f36a99/src/OBJ.cpp#L77-L79

是不是应该改成，基于顶点`a`, `b`, `c`进行轮换的计算，然后再依次赋值：

```cpp
normals[face[0]] += compute_normal_biased(a, b, c); 
normals[face[1]] += compute_normal_biased(b, c, a); 
normals[face[2]] += compute_normal_biased(c, a, b);  
```

**Comment by archibate** [comment]
有道理，应该这样写的，是小彭老师疏忽了











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 下午2:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [parallel101/opengltutor] 问题：计算具有biased的顶点法向量，代码中是不是需要关于顶点做个轮换 (Issue #46)




 
@archibate
 
现代码中，基于顶点a计算出具有biased的顶点法向量后，会依次赋值给a, b, c三个顶点：
 
https://github.com/parallel101/opengltutor/blob/817754a02e03f7b531e6be9366fec3ebb6f36a99/src/OBJ.cpp#L77-L79
 
是不是应该改成，基于顶点a, b, c进行轮换的计算，然后再依次赋值：
 normals[face[0]] += compute_normal_biased(a, b, c);  normals[face[1]] += compute_normal_biased(b, c, a); normals[face[2]] += compute_normal_biased(c, a, b);
